language: node_js
node_js:
  - 8
after_script:
  - NOW_ALIAS=parceljs.org node_modules/.bin/now-travis
branches:
  only:
    - master
env:
  global:
    - secure: >-
        PILwhpm5gInop3CXXHc0Rugq2aSlVXT7rif+tDMRK2ubolhPIHVZI8YzH/XzVCTvj8W6SZ9WrqeX0Yi4mf1tB73Crh5MxB8IiHWpnXfUD+gXrs60k41sYlldtYfhIrzrz8X/ZOuBeP5LGoue5qQH3Vx/nTgtOPIezG0mk7N3TDvPSELsqRVE86IHEn75wCchGV8ZV09Fzr8ROHab+gq7pcnB2fUWnsBbaO3IP5rRHZnNi2d/wAQlRMT5LE0KdHRJvzAvC1B0KToj+cgVFIA6CV4sjr26395djlF81oDT6jXC+BtzSCw1ftsjVvGgXxG4ePZ9d3GpsxT8Q8AW+X08Pgv/DZ9Tm+KBCv6+GstvW9eb9KevFa1CSZbR7XBM9Q/65nqkb6m9Fhuo5iIpP9fIUVAMOvNM8SL+E+VuiKNKxe+QsZ/nbZfHmHWNd5bVyD5FpJ/+nhnuVxZv3OiOSX4vttvzt1i3Iums+Q6dYBgV4tEhTj/nRRPwukCz70L0GqjEU9NFUK6LNlauYjjm5WNxfJvb7hyvg64GYk2fwhUJqNZVFDcqOg9NVY9yaCJCEzA9buhu2ghjRGf8Rc3aZkR1uGVhgeOgDhvhmYxkQmWXnoYU/M+K1fAMsnCdjgJUbeTPXipi1io4BPF6oNuJzDqMIpuYGPqmKl8XeVXB67I9RBw=
    - secure: >-
        V2vpnAOeKCNRN6P/Dp6/qI9Wi5AirXtmGcNknpVxjH7kRxs7JjApGW3Vko7LFz3ZIExGwDDy1s/mJ7Z7ZH5d6fK6SlbOGYJG53pULuo9Zevj1utwJZ/i5HB3PQMCaoPCgmVrASZ7gL3OouYln4y9SvNaQDf4p0qnckoAIf9QrVbC7JBKxXZy0W690zKf/UQpWvJAcF5PXtyfceEXf6SswZmOHZxkLFg4X7lnbgxYAcz+lfkuSgxLHS923cxLJVgZiFcumk06/+irdObWN4khTkLCdwb3XtijQJgaOQI2L4oZAEEq1JRIWVQ2VeDqm/gy8TKjkwwGorQg+26IuTnhR3DMhpw/w3EnGZKeBz4/55xRmfSFXzqB6bAr+ZzNbiXS8GocW51SuB9TpyaHN5C4xexsvQumwTGgMAThFzGH1lFtiOhBHbskrmp3ICtSgJFW5SGLLadtGE0Dl8fMEyuYatkJR7buRpbRBYzgc0sapHEYpysLY8LGBvQhUc9QFzIfMLSwHpkeR9DHDVG9evKuQnMok99Aw1AtQyYM3YvWoT+tTQhookcNApAPfuahdwvmAUNrWI0MJghJbW+ThzFrO49Q+qDs+R4ueU1702aAD2nQ0bK4cX0iw9OhYa/zZFDAtCC3bCKECMi6yb6RP9gKUYiUoXGMVIR8GNdcfU1qY6g=
